name: Build and Release

on:
  push:
    branches:
      - main
    paths:
      - 'ConquestServer.cpp'
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Visual Studio
      uses: ilammy/msvc-dev-cmd@v1

    - name: Configure with CMake
      run: cmake -B build -S . -G "Visual Studio 17 2022" -A Win32

    - name: Build with CMake
      run: cmake --build build --config Release

    - name: Generate Date-Based Tag and Release Name
      run: |
        $DATE = Get-Date -Format "yyyy-MM-dd"
        echo "TAG_NAME=release-$DATE" >> $env:GITHUB_ENV
        echo "RELEASE_NAME=Release $DATE" >> $env:GITHUB_ENV

    - name: Create a GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ env.TAG_NAME }}
        name: ${{ env.RELEASE_NAME }}
        body: |
          This is an automated release performed by GitHub Actions.
        draft: false
        prerelease: false
        files: |
          build/Release/ConquestServer.exe
